# Generated by Django 4.1.7 on 2023-06-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioElement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vo', 'Voice Over'), ('bg_music', 'Background Music'), ('video_music', 'Video Music')], max_length=20)),
                ('high_volume', models.IntegerField()),
                ('low_volume', models.IntegerField()),
                ('video_component_id', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
